"""Isolated regression tests. No real service, queue or /etc file is touched."""
import builtins
import contextlib
import copy
import importlib.util
import io
import itertools
from pathlib import Path
import re
import tempfile
import unittest
from unittest.mock import patch

WEB_PHP = '<?php echo "synthetic web interface";\n'

SCRIPT = Path(__file__).resolve().parents[1] / 'kienzlefax-verwalten.sh'
SOURCE = SCRIPT.read_text().split("<<'KFX_PYTHON'\n", 1)[1].split('\nKFX_PYTHON\n', 1)[0]
spec = importlib.util.spec_from_loader('verwalten', loader=None)
v = importlib.util.module_from_spec(spec)
exec(compile(SOURCE, str(SCRIPT), 'exec'), v.__dict__)

EXT = '''[general]
static=yes
[fax-in]
exten => 12345,1,NoOp(Inbound Fax)
 same => n,Answer()
 same => n,ReceiveFAX(${TIFF})
 same => n,Hangup()
exten => h,1,NoOp(cleanup)
[fax-out]
exten => _0X.,1,NoOp(outgoing)
 same => n,Dial(PJSIP/${EXTEN}@kfx-provider-endpoint)
[kfx-provider-in]
exten => 12345,1,Goto(fax-in,12345,1)
exten => 67890,1,Goto(kfx-phone-in,s,1)
#tryinclude "/etc/asterisk/extensions-kfx-telefonie.conf"
'''
PJSIP = '''; generated by kienzlefax provider template: fixture
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5070
[kfx-provider]
type=registration
server_uri=sip:example.invalid
client_uri=sip:fixture@example.invalid
[kfx-provider-auth]
type=auth
password=synthetic-only\\;never-print
[kfx-provider-endpoint]
type=endpoint
context=kfx-provider-in
#tryinclude "/etc/asterisk/pjsip-kfx-telefonie.conf"
'''
PHONE = '''; generated by kienzlefax telefonie-queue.sh
[transport-kfx-phone]
type=transport
bind=192.0.2.1:5060
[201-auth]
type=auth
password=synthetic-only
[201]
type=aor
max_contacts=1
[201]
type=endpoint
context=kfx-phone-local
[kfx-phone-in-registration]
type=registration
server_uri=sip:example.invalid
[kfx-phone-in-endpoint]
type=endpoint
context=kfx-provider-in
'''
PHONE_EXT = '''[kfx-phone-in]
exten => _X.,1,Goto(s,1)
exten => s,1,NoOp(phone)
 same => n,Goto(kfx-phone-queue,s,1)
[kfx-phone-local]
exten => _X.,1,NoOp(outgoing)
 same => n,Dial(PJSIP/${EXTEN})
[kfx-phone-queue]
exten => s,1,Answer()
 same => n,Queue(praxis,r)
[kfx_external_capacity]
exten => primary-phone,1,NoOp(capacity)
 same => n,Return()
'''
SMB = '''[global]
workgroup = WORKGROUP
[hierhin-scannen-fuer-ocr]
path = /srv/scan/eingang
guest ok = yes
[scan-eingang]
path = /srv/scan/ocr
available = yes
[pdf-zu-fax2]
path = /srv/kienzlefax/pdf-zu-fax2
[unrelated]
path = /srv/other
guest ok = no
'''

# Shared-host layout: another application re-enters [global] after fax shares.
# Keep its settings and unrelated shares byte-for-byte, including print commands.
SHARED_SMB = SMB + '''
# BEGIN OTHER APPLICATION SHARES
[GDT]
path = /srv/fragebogenpi/GDT
force user = www-data
[webroot-lan]
path = /var/www/html
valid users = admin
# END OTHER APPLICATION SHARES

# BEGIN TERMINZETTEL MANAGED
[global]
cache directory = /run/terminzettel/samba-cache
log file = /dev/null
logging = file
log level = 0

[Terminzettel]
path = /run/terminzettel/spool
printable = yes
printing = bsd
print command = /usr/local/sbin/terminzettel-submit "%s"
# END TERMINZETTEL MANAGED

[formularkopf-klebchen]
path = /var/spool/samba/formularkopf-klebchen
printable = yes
printing = cups
'''


def generated_fax_dialplan():
    """Include the footer appended *after* the installer's main heredoc."""
    source = (SCRIPT.parent / 'installer-modular/extensions.sh').read_text()
    text = re.findall(r'cat >"\$EXT" <<\'EOF\'\n(.*?)\nEOF', source, re.S)[-1]
    footer = re.search(r"^printf '\\n(#tryinclude [^']+)\\n' >>\"\$EXT\"$", source, re.M)
    if footer is None:
        raise AssertionError('Installer footer changed; update the complete dialplan fixture.')
    text = text.replace('__KFX_FAX_DID__', '12345')
    text = text.replace('__KFX_PHONE_ROUTE__', 'exten => 67890,1,Goto(kfx-phone-in,s,1)')
    return text + '\n\n' + footer.group(1) + '\n'


class FakeHost(v.Host):
    def __init__(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.files = {}
        self.units = {name: {'active': True, 'enabled': 'enabled', 'frozen': False}
                      for name in (*v.SERVICES.values(), 'asterisk.service', 'smbd.service', 'apache2.service')}
        self.flags = {'fax1': {'enabled': True, 'accepting': True},
                      'fax2': {'enabled': False, 'accepting': True}}
        self.commands = []
        self.writes = []
        self.calls = False
        self.busy = set()
        self.connected = set()
        self.jobs = set()
        self.fail_write = None
        self.queue = 0
        self.put(v.EXT, EXT, 0o640)
        self.put(v.PJSIP, PJSIP, 0o640)
        self.put(v.PHONE_PJSIP, PHONE, 0o640)
        self.put(v.PHONE_EXT, PHONE_EXT, 0o640)
        self.put(v.SMB, SMB)
        self.put(v.WEB, WEB_PHP)
        self.path('/var/www/html/kienzlefax.php').parent.mkdir(parents=True)
        self.path('/var/www/html/kienzlefax.php').touch()

    def close(self):
        self.temp.cleanup()

    def path(self, path):
        return self.root / path.lstrip('/')

    def put(self, path, text, mode=0o644):
        self.files[path] = v.text_snapshot(text, mode=mode)

    def snapshot(self, path):
        return copy.deepcopy(self.files.get(path))

    def write(self, path, snapshot):
        if self.fail_write == path:
            self.fail_write = None
            raise v.Error('simulierter Schreibfehler')
        self.writes.append(path)
        if snapshot is None:
            self.files.pop(path, None)
        else:
            self.files[path] = copy.deepcopy(snapshot)

    def service(self, unit):
        return copy.deepcopy(self.units.get(unit))

    def run(self, *args, **kwargs):
        self.commands.append(args)
        if args[0] == 'cupsreject':
            self.flags[args[1]]['accepting'] = False
        return '', 0

    def ast(self, command):
        raise AssertionError('Live-Dienststeuerung ist im Neustart-Ablauf nicht erlaubt.')

    def idle_calls(self):
        v.require(not self.calls, 'Telefonat oder Fax aktiv.')

    def idle_processing(self, key):
        v.require(key not in self.busy, 'Verarbeitung nicht leer: ' + key)

    def can_freeze(self, unit):
        pass

    def idle_share(self, name):
        v.require(name not in self.connected, 'Verbindung offen: ' + name)

    def idle_printer(self, name):
        v.require(name not in self.jobs, 'Druckauftraege vorhanden: ' + name)

    def freeze(self, unit):
        raise AssertionError('Live-Dienststeuerung ist im Neustart-Ablauf nicht erlaubt.')

    def thaw(self, unit):
        raise AssertionError('Live-Dienststeuerung ist im Neustart-Ablauf nicht erlaubt.')

    def service_active(self, unit, active):
        raise AssertionError('Live-Dienststeuerung ist im Neustart-Ablauf nicht erlaubt.')

    def printers(self):
        return list(self.flags)

    def printer(self, name):
        return copy.deepcopy(self.flags[name])

    def printer_set(self, name, flags):
        self.flags[name] = copy.deepcopy(flags)

    def validate_samba(self, text):
        pass

    def reload(self, paths, disabled, verify=True):
        raise AssertionError('Live-Dienststeuerung ist im Neustart-Ablauf nicht erlaubt.')

    def queue_count(self):
        return self.queue


class ManagementTests(unittest.TestCase):
    def setUp(self):
        self.host = FakeHost()
        self.addCleanup(self.host.close)
        self.manager = v.Manager(self.host)

    def apply(self, disabled):
        plan = self.manager.plan(set(disabled))
        self.manager.apply(plan)
        return plan

    def test_inventory_individual_components(self):
        found = self.manager.inventory()
        self.assertIn('scan_ocr', found)
        self.assertIn('fax_ocr', found)
        self.assertIn('share:scan-eingang', found)
        self.assertIn('share:pdf-zu-fax2', found)
        self.assertIn('printer:fax2', found)
        self.assertNotIn('share:unrelated', found)

    def test_single_share_restores_exact_file_and_permissions(self):
        before = self.host.snapshot(v.SMB)
        self.apply({'share:scan-eingang'})
        content = v.snapshot_text(self.host.snapshot(v.SMB))
        self.assertIn('[scan-eingang]\n   available = no\n', content)
        self.assertIn('[unrelated]\npath = /srv/other\nguest ok = no\n', content)
        self.apply(set())
        self.assertEqual(self.host.snapshot(v.SMB), before)

    def test_shared_file_reenable_one_keeps_other_paused(self):
        self.apply({'share:scan-eingang', 'share:pdf-zu-fax2'})
        self.apply({'share:pdf-zu-fax2'})
        content = v.snapshot_text(self.host.snapshot(v.SMB))
        self.assertIn('[scan-eingang]\npath = /srv/scan/ocr\navailable = yes', content)
        self.assertIn('[pdf-zu-fax2]\n   available = no', content)

    def test_undo_last_only_returns_previous_combination(self):
        self.apply({'share:scan-eingang'})
        second = self.apply({'share:scan-eingang', 'web'})
        self.manager.rollback(second)
        self.assertEqual(self.manager.state['disabled'], ['share:scan-eingang'])
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)
        self.assertIn('available = no', v.snapshot_text(self.host.snapshot(v.SMB)))

    def test_service_roundtrip_restores_original_runtime_without_enable(self):
        self.host.units['scan-ocr.service']['active'] = False
        self.host.units['scan-ocr.service']['enabled'] = 'disabled'
        self.apply({'scan_ocr'})
        self.assertIn('ConditionPathExists=!', v.snapshot_text(self.host.snapshot(v.dropin('scan-ocr.service'))))
        self.apply(set())
        self.assertFalse(self.host.units['scan-ocr.service']['active'])
        self.assertEqual(self.host.units['scan-ocr.service']['enabled'], 'disabled')
        self.assertIsNone(self.host.snapshot(v.dropin('scan-ocr.service')))

    def test_active_service_roundtrip_only_changes_boot_configuration(self):
        original = copy.deepcopy(self.host.units)
        self.apply({'scan_ocr'})
        self.assertIsNotNone(self.host.snapshot(v.dropin('scan-ocr.service')))
        self.assertEqual(self.host.units, original)
        self.apply(set())
        self.assertIsNone(self.host.snapshot(v.dropin('scan-ocr.service')))
        self.assertEqual(self.host.units, original)

    def test_active_work_does_not_block_boot_configuration(self):
        self.host.busy.add('scan_ocr')
        self.host.calls = True
        self.host.connected.add('scan-eingang')
        original = copy.deepcopy(self.host.units)
        self.apply({'scan_ocr', 'fax_receive', 'share:scan-eingang'})
        self.assertEqual(self.host.units, original)
        self.assertIsNotNone(self.host.snapshot(v.dropin('scan-ocr.service')))

    def test_apply_and_restore_never_control_running_services(self):
        original = copy.deepcopy(self.host.units)
        desired = {'fax_send', 'fax_receive', 'fax_ocr', 'phone', 'scan_ocr', 'web', 'share:scan-eingang'}
        with patch.object(self.host, 'freeze', side_effect=AssertionError('no freeze')), \
                patch.object(self.host, 'thaw', side_effect=AssertionError('no thaw')), \
                patch.object(self.host, 'service_active', side_effect=AssertionError('no start/stop')), \
                patch.object(self.host, 'reload', side_effect=AssertionError('no reload')), \
                patch.object(self.host, 'ast', side_effect=AssertionError('no Asterisk CLI')):
            plan = self.apply(desired)
            self.manager.rollback(plan)
        self.assertEqual(self.host.units, original)
        self.assertFalse(any(cmd[0] in ('systemctl', 'asterisk', 'smbcontrol', 'smbclient') for cmd in self.host.commands))

    def test_paused_scanner_can_resume_with_new_input(self):
        self.apply({'scan_ocr'})
        self.host.busy.add('scan_ocr')
        self.apply(set())
        self.assertTrue(self.host.units['scan-ocr.service']['active'])

    def test_restore_reactivation_does_not_stop_busy_scanner(self):
        self.apply({'scan_ocr'})
        plan = self.apply(set())
        self.host.busy.add('scan_ocr')
        self.manager.rollback(plan)
        self.assertTrue(self.host.units['scan-ocr.service']['active'])
        self.assertIsNotNone(self.host.snapshot(v.dropin('scan-ocr.service')))

    def test_legacy_pending_restore_ignores_frozen_restart_and_stopped_worker(self):
        plan = self.manager.plan({'fax_send', 'fax_receive', 'fax_ocr', 'web', 'share:scan-eingang'})
        plan['before_state']['version'] = '0.1.4'
        self.manager.save(v.PENDING, plan)
        for path, value in plan['after_files'].items():
            self.host.write(path, value)
        self.host.units['scan-ocr-fax.service'].update(active=False, frozen=True)
        self.host.units['kienzlefax-worker.service'].update(active=False)
        original_runtime = copy.deepcopy(self.host.units)
        with patch.object(self.host, 'service', side_effect=AssertionError('no runtime status required')):
            self.manager.rollback(plan, pending=True)
        self.assertEqual(self.host.units, original_runtime)
        for path, value in plan['before_files'].items():
            self.assertEqual(self.host.snapshot(path), value)
        self.assertIsNone(self.host.snapshot(v.PENDING))
        self.assertEqual(self.manager.load(v.LAST)['status'], 'restored')

    def test_recovery_after_interrupted_restore(self):
        plan = self.apply({'share:scan-eingang', 'web'})
        self.host.fail_write = v.WEB
        with self.assertRaises(v.Error):
            self.manager.rollback(plan)
        pending = self.manager.load(v.PENDING)
        self.assertEqual(pending['status'], 'restoring')
        self.manager.rollback(pending, pending=True)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.SMB)), SMB)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)

    def test_fax_off_keeps_phone_and_transports(self):
        phone = self.host.snapshot(v.PHONE_PJSIP)
        self.apply({'fax_send', 'fax_receive'})
        pjsip = v.snapshot_text(self.host.snapshot(v.PJSIP))
        self.assertNotIn('type=registration', pjsip)
        self.assertIn('type=transport', pjsip)
        self.assertIn('#tryinclude', pjsip)
        self.assertEqual(self.host.snapshot(v.PHONE_PJSIP), phone)
        self.assertFalse(any(cmd[0] == 'asterisk' for cmd in self.host.commands))

    def test_fax_receive_only_keeps_outbound_registration(self):
        original = self.host.snapshot(v.PJSIP)
        self.apply({'fax_receive'})
        self.assertEqual(original, self.host.snapshot(v.PJSIP))

    def test_entry_patch_preserves_inflight_priorities_and_runtime_variables(self):
        transformed = v.block_entries(EXT, {'fax-in'}, allowed_file_includes=(v.PHONE_DIALPLAN_INCLUDE,))
        self.assertIn('exten => 12345,1,Hangup(17)', transformed)
        self.assertIn(' same => n,ReceiveFAX(${TIFF})', transformed)
        self.assertIn('exten => h,1,NoOp(cleanup)', transformed)
        self.assertIn('exten => 67890,1,Goto(kfx-phone-in,s,1)', transformed)

    def test_phone_off_preserves_fax_capacity_and_transport(self):
        fax = self.host.snapshot(v.PJSIP)
        self.apply({'phone'})
        content = v.snapshot_text(self.host.snapshot(v.PHONE_PJSIP))
        self.assertIn('type=transport', content)
        self.assertNotIn('type=endpoint', content)
        self.assertNotIn('type=registration', content)
        self.assertEqual(fax, self.host.snapshot(v.PJSIP))
        self.assertIn('exten => primary-phone,1,NoOp(capacity)', v.snapshot_text(self.host.snapshot(v.PHONE_EXT)))

    def test_fax_ocr_cannot_stop_with_receive_active(self):
        with self.assertRaisesRegex(v.Error, 'Fax-OCR'):
            self.manager.plan({'fax_ocr'})
        self.assertFalse(self.host.writes)

    def test_fax_ocr_and_receive_can_stop_together(self):
        self.apply({'fax_receive', 'fax_ocr'})
        self.assertTrue(self.host.units['scan-ocr-fax.service']['active'])
        self.assertIsNotNone(self.host.snapshot(v.dropin('scan-ocr-fax.service')))
        self.assertTrue(self.host.units['scan-ocr.service']['active'])

    def test_receive_reenable_requires_ocr_running(self):
        self.apply({'fax_receive', 'fax_ocr'})
        with self.assertRaises(v.Error):
            self.manager.plan({'fax_ocr'})
        self.apply(set())
        self.assertTrue(self.host.units['scan-ocr-fax.service']['active'])

    def test_scanner_pause_independent_of_fax_ocr(self):
        self.apply({'scan_ocr'})
        self.assertTrue(self.host.units['scan-ocr-fax.service']['active'])

    def test_manual_pjsip_refused(self):
        self.host.put(v.PJSIP, PJSIP.replace('; generated by kienzlefax provider template:', '; user custom'))
        with self.assertRaisesRegex(v.Error, 'Manuelle'):
            self.manager.plan({'fax_send', 'fax_receive'})
        self.assertFalse(self.host.writes)

    def test_additional_pjsip_registration_refused(self):
        self.host.put(v.PJSIP, PJSIP + '\n[other]\ntype=registration\n')
        with self.assertRaisesRegex(v.Error, 'Mehrere'):
            self.manager.plan({'fax_send', 'fax_receive'})

    def test_config_drift_refuses_apply_and_restore(self):
        plan = self.apply({'share:scan-eingang'})
        self.host.put(v.SMB, 'external changes')
        with self.assertRaisesRegex(v.Error, 'extern geaendert'):
            self.manager.plan(set())
        with self.assertRaisesRegex(v.Error, 'extern geaendert'):
            self.manager.rollback(plan)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.SMB)), 'external changes')

    def test_config_change_after_preview_refused(self):
        plan = self.manager.plan({'share:scan-eingang'})
        self.host.put(v.SMB, 'external changes')
        with self.assertRaises(v.Error):
            self.manager.apply(plan)
        self.assertFalse(self.host.writes)

    def test_service_drift_detected(self):
        self.apply({'fax_send'})
        self.host.units['kienzlefax-worker.service']['enabled'] = 'disabled'
        self.assertTrue(self.manager.drift())
        with self.assertRaises(v.Error):
            self.manager.plan(set())

    def test_idempotent_noop(self):
        self.apply({'web'})
        writes = len(self.host.writes)
        self.assertIsNone(self.manager.plan({'web'}))
        self.assertEqual(len(self.host.writes), writes)

    def test_write_failure_rolls_back_exact_state(self):
        before = copy.deepcopy(self.host.files)
        self.host.fail_write = v.WEB
        with self.assertRaisesRegex(v.Error, 'wiederhergestellt'):
            self.apply({'fax_send', 'fax_receive', 'share:scan-eingang', 'web'})
        for path, value in before.items():
            self.assertEqual(self.host.snapshot(path), value)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)
        self.assertIsNone(self.host.snapshot(v.PENDING))
        self.assertTrue(self.host.units['kienzlefax-worker.service']['active'])
        self.assertFalse(self.manager.state['disabled'])

    def test_crash_recovery_accepts_mixture_of_before_and_after(self):
        plan = self.manager.plan({'web', 'share:scan-eingang'})
        self.manager.save(v.PENDING, plan)
        self.host.write(v.WEB, plan['after_files'][v.WEB])
        self.manager.rollback(plan, pending=True)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.SMB)), SMB)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)
        self.assertIsNone(self.host.snapshot(v.PENDING))

    def test_pending_crash_blocks_other_operations(self):
        plan = self.manager.plan({'web'})
        self.manager.save(v.PENDING, plan)
        with self.assertRaisesRegex(v.Error, 'Unvollstaendige'):
            self.manager.plan({'scan_ocr'})

    def test_printer_roundtrip_preserves_independent_flags(self):
        original = copy.deepcopy(self.host.flags)
        self.apply({'printer:fax1', 'printer:fax2'})
        self.assertEqual(self.host.flags['fax2'], {'enabled': False, 'accepting': False})
        self.apply(set())
        self.assertEqual(self.host.flags, original)

    def test_queued_print_job_refuses_before_mutation(self):
        self.host.jobs.add('fax1')
        with self.assertRaisesRegex(v.Error, 'Druckauftraege'):
            self.manager.plan({'printer:fax1'})
        self.assertFalse(self.host.writes)

    def test_web_file_is_backed_up_removed_and_restored_without_apache(self):
        self.host.files[v.WEB].update(mode=0o640, uid=33, gid=33)
        original = self.host.snapshot(v.WEB)
        self.apply({'web'})
        self.assertIsNone(self.host.snapshot(v.WEB))
        self.assertEqual(self.manager.state['files'][v.WEB]['original'], original)
        self.assertLess(self.host.writes.index(v.PENDING), self.host.writes.index(v.WEB))
        self.assertEqual(self.host.snapshot(v.STATE_FILE)['mode'], 0o600)
        self.assertIn('web', self.manager.inventory())
        self.apply(set())
        self.assertEqual(self.host.snapshot(v.WEB), original)
        self.assertFalse(any(command[0] in ('apache2ctl', 'curl', 'systemctl') for command in self.host.commands))
        self.assertFalse(any(path.startswith('/etc/apache2/') for path in self.host.writes))

    def test_web_reactivation_never_overwrites_a_new_php_file(self):
        self.apply({'web'})
        self.host.put(v.WEB, '<?php // newer installation\n')
        replacement = self.host.snapshot(v.WEB)
        with self.assertRaisesRegex(v.Error, 'extern geaendert'):
            self.manager.plan(set())
        self.assertEqual(self.host.snapshot(v.WEB), replacement)

    def test_legacy_apache_web_pause_can_still_be_restored(self):
        self.host.put(v.LEGACY_WEB, '# old wizard block\nRequire all denied\n')
        self.manager.state['disabled'] = ['web']
        self.manager.state['files'][v.LEGACY_WEB] = {
            'original': None, 'applied': self.host.snapshot(v.LEGACY_WEB)}
        self.apply(set())
        self.assertIsNone(self.host.snapshot(v.LEGACY_WEB))
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)

    def test_secret_contents_never_printed_in_status(self):
        self.apply({'fax_send', 'fax_receive'})
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            v.show_status(self.manager)
        self.assertNotIn('synthetic-only', output.getvalue())
        for path, snap in self.host.files.items():
            if path.startswith(v.STATE_DIR):
                self.assertEqual(snap['mode'], 0o600)

    def test_unknown_component_refused(self):
        with self.assertRaises(v.Error):
            self.manager.plan({'share:unrelated'})

    def test_include_and_duplicate_samba_refused(self):
        for text in (SMB + '\ninclude = /etc/other\n', SMB + '\n[SCAN-EINGANG]\npath=/other\n'):
            with self.subTest(text=text):
                self.host.put(v.SMB, text)
                with self.assertRaises(v.Error):
                    self.manager.plan({'share:scan-eingang'})

    def test_repeated_global_inventory_and_status_are_read_only(self):
        self.host.put(v.SMB, SHARED_SMB)
        found = self.manager.inventory()
        self.assertEqual(found.count('share:scan-eingang'), 1)
        for name in ('global', 'gdt', 'webroot-lan', 'terminzettel', 'formularkopf-klebchen'):
            self.assertNotIn('share:' + name, found)
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertFalse(v.show_status(self.manager))
        self.assertFalse(self.host.writes)

    def test_repeated_global_does_not_block_unrelated_web_change(self):
        self.host.put(v.SMB, SHARED_SMB)
        before = self.host.snapshot(v.SMB)
        self.apply({'web'})
        self.assertEqual(self.host.snapshot(v.SMB), before)
        self.assertNotIn(v.SMB, self.host.writes)

    def test_repeated_global_share_change_preserves_other_applications(self):
        self.host.put(v.SMB, SHARED_SMB, mode=0o640)
        before = self.host.snapshot(v.SMB)
        self.apply({'share:scan-eingang'})
        expected = SHARED_SMB.replace('[scan-eingang]\npath = /srv/scan/ocr\navailable = yes\n',
                                      '[scan-eingang]\n   available = no\npath = /srv/scan/ocr\n')
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.SMB)), expected)
        self.assertEqual(self.host.snapshot(v.SMB)['mode'], before['mode'])
        self.apply(set())
        self.assertEqual(self.host.snapshot(v.SMB), before)

    def test_repeated_global_undo_restores_original_file(self):
        self.host.put(v.SMB, SHARED_SMB, mode=0o640)
        before = self.host.snapshot(v.SMB)
        plan = self.apply({'share:scan-eingang', 'web'})
        self.manager.rollback(plan)
        self.assertEqual(self.host.snapshot(v.SMB), before)
        self.assertEqual(v.snapshot_text(self.host.snapshot(v.WEB)), WEB_PHP)

    def test_repeated_global_is_case_insensitive(self):
        self.host.put(v.SMB, SMB + '\n[ GLOBAL ]\nlog level = 0\n')
        self.assertIn('share:scan-eingang', self.manager.inventory())
        self.apply({'share:scan-eingang'})
        self.assertIn('[ GLOBAL ]\nlog level = 0\n', v.snapshot_text(self.host.snapshot(v.SMB)))

    def test_other_samba_share_with_spaces_and_dollar_is_preserved(self):
        extra = '\n[print$]\npath=/drivers\n[Our documents]\npath=/documents\n'
        self.host.put(v.SMB, SMB + extra)
        self.apply({'share:scan-eingang'})
        self.assertIn(extra, v.snapshot_text(self.host.snapshot(v.SMB)))

    def test_all_valid_core_switch_combinations_roundtrip(self):
        keys = list(v.LABELS)
        baseline = {path: self.host.snapshot(path) for path in (v.EXT, v.PJSIP, v.PHONE_EXT, v.PHONE_PJSIP)}
        for flags in itertools.product((False, True), repeat=len(keys)):
            selected = {key for key, flag in zip(keys, flags) if flag}
            if not selected or ('fax_ocr' in selected and 'fax_receive' not in selected):
                continue
            with self.subTest(selected=selected):
                self.apply(selected)
                self.apply(set())
                for path, original in baseline.items():
                    self.assertEqual(self.host.snapshot(path), original)
                self.assertTrue(all(self.host.units[name]['active'] for name in v.SERVICES.values()))

    def test_actual_generated_dialplans_keep_all_following_priorities(self):
        root = SCRIPT.parent
        fax = generated_fax_dialplan()
        phone_script = (root / 'installer-modular/telefonie-queue.sh').read_text()
        phone = re.search(r'cat >"\$EXTENSIONS_TMP" <<\'EOF\'\n(.*?)\nEOF', phone_script, re.S).group(1)
        for original, contexts, allowed in ((fax, {'fax-in'}, (v.PHONE_DIALPLAN_INCLUDE,)),
                                            (phone, v.PHONE_CONTEXTS, ())):
            with self.subTest(contexts=contexts):
                result = v.block_entries(original, contexts, allowed_file_includes=allowed)
                unchanged_before = [line for line in original.splitlines() if not line.strip().startswith('exten')]
                unchanged_after = [line for line in result.splitlines() if not line.strip().startswith('exten')]
                self.assertEqual(unchanged_before, unchanged_after)
                self.assertIn('${', result)

    def test_installer_footer_fax_pause_preserves_phone_include(self):
        original = generated_fax_dialplan()
        self.host.put(v.EXT, original, mode=0o640)
        phone = self.host.snapshot(v.PHONE_EXT)
        self.apply({'fax_receive'})
        updated = v.snapshot_text(self.host.snapshot(v.EXT))
        self.assertTrue(updated.endswith('#tryinclude "/etc/asterisk/extensions-kfx-telefonie.conf"\n'))
        self.assertEqual(updated.count('#tryinclude'), original.count('#tryinclude'))
        self.assertEqual(updated, original.replace('exten => 12345,1,NoOp(Inbound Fax)',
                                                  'exten => 12345,1,Hangup(17) ; KienzleFax Verwaltung'))
        self.assertEqual(self.host.snapshot(v.PHONE_EXT), phone)

    def test_installer_footer_fax_shutdown_roundtrip_and_undo(self):
        self.host.put(v.EXT, generated_fax_dialplan(), mode=0o640)
        before = copy.deepcopy(self.host.files)
        plan = self.apply({'fax_send', 'fax_receive', 'share:scan-eingang'})
        self.manager.rollback(plan)
        for path in (v.EXT, v.PJSIP, v.PHONE_EXT, v.PHONE_PJSIP, v.SMB):
            self.assertEqual(self.host.snapshot(path), before[path])
        self.apply({'fax_send', 'fax_receive'})
        self.apply(set())
        self.assertEqual(self.host.snapshot(v.EXT), before[v.EXT])

    def test_installer_footer_keeps_unknown_directives_blocked(self):
        for directive in ('include => other-context', 'switch => Realtime/other',
                          'eswitch => other', 'lswitch => other', '#exec /bin/true',
                          '#tryinclude "/etc/asterisk/other.conf"'):
            with self.subTest(directive=directive):
                self.host.put(v.EXT, generated_fax_dialplan() + directive + '\n')
                with self.assertRaises(v.Error):
                    self.manager.plan({'fax_receive'})
                self.assertFalse(self.host.writes)

    def test_installer_footer_is_not_implicitly_allowed_in_phone_file(self):
        self.host.put(v.PHONE_EXT, PHONE_EXT + '\n#tryinclude "/etc/asterisk/extensions-kfx-telefonie.conf"\n')
        with self.assertRaises(v.Error):
            self.manager.plan({'phone'})
        self.assertFalse(self.host.writes)

    def test_runtime_service_change_after_preview_does_not_block_saving(self):
        plan = self.manager.plan({'fax_send'})
        self.host.units['kienzlefax-worker.service'].update(active=False, frozen=True)
        self.manager.apply(plan)
        self.assertIsNotNone(self.host.snapshot(v.dropin('kienzlefax-worker.service')))

    def test_dry_run_interactive_has_no_writes(self):
        values = ['d' if key == 'web' else 'u' for key in self.manager.inventory()]
        with patch.object(v.sys, 'platform', 'linux'), patch.object(v.os, 'geteuid', return_value=0), \
                patch.object(v, 'Host', return_value=self.host), patch.object(builtins, 'input', side_effect=values), \
                contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(v.main(['--dry-run']), 0)
        self.assertFalse(self.host.writes)
        self.assertFalse(self.host.path(v.STATE_DIR).exists())

    def test_eof_dialog_has_no_writes(self):
        with patch.object(v.sys, 'platform', 'linux'), patch.object(v.os, 'geteuid', return_value=0), \
                patch.object(v, 'Host', return_value=self.host), patch.object(builtins, 'input', side_effect=EOFError), \
                contextlib.redirect_stdout(io.StringIO()):
            with self.assertRaises(v.Error):
                v.main([])
        self.assertFalse(self.host.writes)
        self.assertFalse(self.host.path(v.STATE_DIR).exists())

    def test_queue_reactivation_requires_explicit_consent(self):
        self.host.queue = 2
        with patch.object(builtins, 'input', return_value=''), contextlib.redirect_stdout(io.StringIO()):
            with self.assertRaises(v.Error):
                v.confirm_queue(self.host)


class HostTests(unittest.TestCase):
    def test_command_error_names_systemctl_operation_and_unit_without_outputs(self):
        result = v.subprocess.CompletedProcess([], 1, stdout='private output', stderr='private diagnostic')
        with patch.object(v.subprocess, 'run', return_value=result):
            with self.assertRaises(v.Error) as caught:
                v.Host().run('systemctl', 'start', 'scan-ocr-fax.service')
        message = str(caught.exception)
        self.assertIn('systemctl start scan-ocr-fax.service', message)
        self.assertIn('Exit-Code 1', message)
        self.assertNotIn('private', message)

    def test_inventory_reads_frozen_queued_restart_without_waiting(self):
        host = v.Host()
        status = ('LoadState=loaded\nUnitFileState=enabled\nFreezerState=frozen\n'
                  'ActiveState=activating\nSubState=auto-restart-queued\n', 0)
        with patch.object(host, 'run', return_value=status) as run, patch.object(v.time, 'sleep') as sleep:
            self.assertEqual(host.service('scan-ocr-fax.service'),
                             {'active': False, 'enabled': 'enabled', 'frozen': True})
        self.assertEqual(run.call_count, 1)
        self.assertEqual(run.call_args.args[:2], ('systemctl', 'show'))
        sleep.assert_not_called()

    def test_atomic_write_preserves_permissions_and_never_follows_symlink(self):
        import os
        host = v.Host()
        with tempfile.TemporaryDirectory() as temp:
            # Resolve macOS /var -> /private/var before exercising the Linux path guard.
            root = Path(temp).resolve()
            path = root / 'config'
            snap = v.text_snapshot('secret', mode=0o600)
            snap.update(uid=os.geteuid(), gid=os.getegid())
            host.write(str(path), snap)
            self.assertEqual(host.snapshot(str(path)), snap)
            target = root / 'alias'
            target.symlink_to(path)
            with self.assertRaises(v.Error):
                host.write(str(target), snap)
            self.assertEqual(path.read_text(), 'secret')

    def test_missing_service_is_not_a_fatal_inventory_error(self):
        host = v.Host()
        with patch.object(host, 'run', return_value=('LoadState=not-found\nActiveState=inactive\n', 4)):
            self.assertIsNone(host.service('nonexistent.service'))

    def test_printer_parse_printing_disabled_and_rejecting(self):
        host = v.Host()
        with patch.object(host, 'run', side_effect=[('printer fax1 disabled since today\n', 0),
                                                  ('fax1 not accepting requests since today\n', 0)]):
            self.assertEqual(host.printer('fax1'), {'enabled': False, 'accepting': False})
        with patch.object(host, 'run', side_effect=[('printer fax1 is printing fax1-42. enabled since today\n', 0),
                                                  ('fax1 accepting requests since today\n', 0)]):
            self.assertEqual(host.printer('fax1'), {'enabled': True, 'accepting': True})

    def test_symlink_and_hardlink_snapshots_refused(self):
        with tempfile.TemporaryDirectory() as temp:
            file = Path(temp) / 'config'
            file.write_text('data')
            link = Path(temp) / 'symlink'
            link.symlink_to(file)
            with self.assertRaises(v.Error):
                v.Host().snapshot(str(link))
            import os
            os.link(file, Path(temp) / 'hardlink')
            with self.assertRaises(v.Error):
                v.Host().snapshot(str(file))


if __name__ == '__main__':
    unittest.main()
