#!/usr/bin/env bash
# IMMER verwenden wenn der ausgewaehlte Fax-Provider als PJSIP-Trunk eingerichtet oder aktualisiert wird.
set -euo pipefail

ENVFILE="/etc/kienzlefax-installer.env"
if [ -f "$ENVFILE" ]; then
  # shellcheck disable=SC1090
  source "$ENVFILE"
fi

KFX_PROVIDER="${KFX_PROVIDER:-1und1}"
if [[ "$KFX_PROVIDER" == "manual" ]]; then
  echo "[INFO] Provider steht auf manuell; pjsip.conf wird nicht automatisch geschrieben."
  echo "[INFO] Bitte /etc/asterisk/pjsip.conf selbst anlegen/anpassen und Endpoint '${KFX_PJSIP_ENDPOINT:-kfx-provider-endpoint}' verwenden."
  if [[ -f /etc/asterisk/pjsip.conf ]] \
    && ! grep -Fxq '#tryinclude "/etc/asterisk/pjsip-kfx-telefonie.conf"' /etc/asterisk/pjsip.conf; then
    cp -a /etc/asterisk/pjsip.conf "/etc/asterisk/pjsip.conf.old.kienzlefax.$(date +%Y%m%d-%H%M%S)"
    printf '\n#tryinclude "/etc/asterisk/pjsip-kfx-telefonie.conf"\n' >>/etc/asterisk/pjsip.conf
  fi
  exit 0
fi

PJSIP_USER="${PJSIP_USER:-${KFX_SIP_USER:-${KFX_SIP_NUMBER:-}}}"
PJSIP_PASS="${PJSIP_PASS:-${KFX_SIP_PASSWORD:-}}"
SIP_BIND_PORT="${SIP_BIND_PORT:-${PJSIP_PORT:-${PJSIP_BIND_PORT:-${KFX_SIP_BIND_PORT:-5070}}}}"
PJSIP_EXPIRATION="${PJSIP_EXPIRATION:-${KFX_SIP_EXPIRATION:-300}}"
PUBLIC_FQDN="${PUBLIC_FQDN:-${KFX_PUBLIC_FQDN:-}}"

PROVIDER_LABEL="${KFX_PROVIDER_LABEL:-$KFX_PROVIDER}"
PROVIDER_DOMAIN="${KFX_SIP_DOMAIN:-}"
PJSIP_OUTBOUND_PROXY="${PJSIP_OUTBOUND_PROXY:-${KFX_SIP_OUTBOUND_PROXY:-}}"
PJSIP_IDENTIFY_MATCH="${PJSIP_IDENTIFY_MATCH:-${KFX_SIP_IDENTIFY_MATCH:-}}"

case "$KFX_PROVIDER" in
  1und1)
    PROVIDER_DOMAIN="${PROVIDER_DOMAIN:-sip.1und1.de}"
    PJSIP_IDENTIFY_MATCH="${PJSIP_IDENTIFY_MATCH:-212.227.0.0/16}"
    ;;
  telekom)
    PROVIDER_DOMAIN="${PROVIDER_DOMAIN:-tel.t-online.de}"
    ;;
  sipgate)
    PROVIDER_DOMAIN="${PROVIDER_DOMAIN:-sipgate.de}"
    ;;
esac

REG_NAME="${KFX_PJSIP_REGISTRATION:-kfx-provider}"
AUTH_NAME="${KFX_PJSIP_AUTH:-kfx-provider-auth}"
AOR_NAME="${KFX_PJSIP_AOR:-kfx-provider-aor}"
ENDPOINT_NAME="${KFX_PJSIP_ENDPOINT:-kfx-provider-endpoint}"
IDENTIFY_NAME="${KFX_PJSIP_IDENTIFY:-kfx-provider-identify}"

PJSIP_CLIENT_URI="${PJSIP_CLIENT_URI:-${KFX_PJSIP_CLIENT_URI:-}}"
if [ -z "$PJSIP_CLIENT_URI" ]; then
  PJSIP_CLIENT_URI="sip:${PJSIP_USER}@${PROVIDER_DOMAIN}"
fi

if [ -z "${PJSIP_USER}" ] || [ -z "${PJSIP_PASS}" ] || [ -z "${PROVIDER_DOMAIN}" ]; then
  echo "ERROR: SIP-User, SIP-Passwort oder Provider-Domain fehlen." >&2
  exit 1
fi
if ! [[ "${SIP_BIND_PORT}" =~ ^[0-9]+$ ]]; then
  echo "ERROR: SIP_BIND_PORT ungueltig: '${SIP_BIND_PORT}'" >&2
  exit 1
fi
if ! [[ "${PJSIP_EXPIRATION}" =~ ^[0-9]+$ ]]; then
  echo "ERROR: PJSIP_EXPIRATION ungueltig: '${PJSIP_EXPIRATION}'" >&2
  exit 1
fi

ast_cfg_value() {
  local s="${1-}"
  s="${s//\\/\\\\}"
  s="${s//;/\\;}"
  printf '%s' "$s"
}

PJSIP_PASS_CFG="$(ast_cfg_value "$PJSIP_PASS")"

wait_for_asterisk_cli() {
  local timeout="${1:-60}"
  local waited=0
  command -v asterisk >/dev/null 2>&1 || return 1
  while (( waited < timeout )); do
    if asterisk -rx "core show version" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  return 1
}

registration_status() {
  local out
  out="$(asterisk -rx "pjsip show registrations" 2>/dev/null || true)"
  awk -v reg="${REG_NAME}/" 'index($1, reg) == 1 {print $3; found=1} END {if (!found) print ""}' <<<"$out"
}

wait_for_registration() {
  local timeout="${1:-30}"
  local waited=0
  local status=""
  command -v asterisk >/dev/null 2>&1 || return 0
  while (( waited < timeout )); do
    status="$(registration_status)"
    if [[ "$status" == "Registered" ]]; then
      echo "[INFO] PJSIP registration status: Registered"
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
  done
  status="$(registration_status)"
  echo "[WARN] PJSIP registration not registered after ${timeout}s (status=${status:-unknown})"
  return 1
}

PJSIP="/etc/asterisk/pjsip.conf"
cp -a "$PJSIP" "${PJSIP}.old.kienzlefax.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true

OUTBOUND_PROXY_LINE=""
if [ -n "${PJSIP_OUTBOUND_PROXY}" ]; then
  if [[ "${PJSIP_OUTBOUND_PROXY}" =~ ^sip: ]]; then
    OUTBOUND_PROXY_LINE="outbound_proxy=${PJSIP_OUTBOUND_PROXY}\;lr"
  else
    OUTBOUND_PROXY_LINE="outbound_proxy=sip:${PJSIP_OUTBOUND_PROXY}\;lr"
  fi
fi

if [ -n "${PUBLIC_FQDN}" ]; then
  EXTERNAL_ADDR_LINES=$(
    cat <<EOF
external_signaling_address = ${PUBLIC_FQDN}
external_media_address     = ${PUBLIC_FQDN}
EOF
  )
else
  EXTERNAL_ADDR_LINES=$(
    cat <<'EOF'
;external_signaling_address = <PUBLIC_FQDN>
;external_media_address     = <PUBLIC_FQDN>
EOF
  )
fi

IDENTIFY_BLOCK=""
if [ -n "${PJSIP_IDENTIFY_MATCH}" ]; then
  IDENTIFY_BLOCK=$(
    cat <<EOF
[${IDENTIFY_NAME}]
type=identify
endpoint=${ENDPOINT_NAME}
match=${PJSIP_IDENTIFY_MATCH}
EOF
  )
else
  IDENTIFY_BLOCK=$(
    cat <<EOF
;[${IDENTIFY_NAME}]
;type=identify
;endpoint=${ENDPOINT_NAME}
;match=<provider-ip-or-network>
EOF
  )
fi

cat >"$PJSIP" <<EOF
; generated by kienzlefax provider template: ${PROVIDER_LABEL}

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:${SIP_BIND_PORT}

${EXTERNAL_ADDR_LINES}

local_net = 10.0.0.0/8
local_net = 192.168.0.0/16

[${REG_NAME}]
type=registration
transport=transport-udp
outbound_auth=${AUTH_NAME}
server_uri=sip:${PROVIDER_DOMAIN}
client_uri=${PJSIP_CLIENT_URI}
contact_user=${PJSIP_USER}
retry_interval=60
forbidden_retry_interval=600
expiration=${PJSIP_EXPIRATION}
${OUTBOUND_PROXY_LINE}

[${AUTH_NAME}]
type=auth
auth_type=userpass
username=${PJSIP_USER}
password=${PJSIP_PASS_CFG}

[${AOR_NAME}]
type=aor
contact=sip:${PROVIDER_DOMAIN}

[${ENDPOINT_NAME}]
type=endpoint
transport=transport-udp
context=kfx-provider-in
disallow=all
allow=alaw,ulaw
outbound_auth=${AUTH_NAME}
aors=${AOR_NAME}
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes
t38_udptl=no
;t38_udptl_ec=no
t38_udptl_nat=no
from_user=${PJSIP_USER}
from_domain=${PROVIDER_DOMAIN}
send_pai=yes
send_rpid=yes
trust_id_outbound=yes
${OUTBOUND_PROXY_LINE}

; ===== JITTERBUFFER (PJSIP/chan_pjsip korrekt) =====
;use_jitterbuffer=yes
;jbimpl=adaptive
;jbmaxsize=400
;jbtargetextra=200

${IDENTIFY_BLOCK}
EOF

printf '\n#tryinclude "/etc/asterisk/pjsip-kfx-telefonie.conf"\n' >>"$PJSIP"

chmod 0640 "$PJSIP" || true
chown root:asterisk "$PJSIP" 2>/dev/null || true

echo "[INFO] Wrote: $PJSIP"
echo "[INFO] Provider=${PROVIDER_LABEL}"
echo "[INFO] Endpoint=${ENDPOINT_NAME}"
echo "[INFO] SIP_USER=${PJSIP_USER}"
echo "[INFO] SIP_DOMAIN=${PROVIDER_DOMAIN}"
echo "[INFO] SIP_BIND_PORT=${SIP_BIND_PORT}"
echo "[INFO] PJSIP_EXPIRATION=${PJSIP_EXPIRATION}"
[ -n "${PJSIP_OUTBOUND_PROXY}" ] && echo "[INFO] OUTBOUND_PROXY=${PJSIP_OUTBOUND_PROXY}" || true
[ -n "${PJSIP_IDENTIFY_MATCH}" ] && echo "[INFO] IDENTIFY_MATCH=${PJSIP_IDENTIFY_MATCH}" || true
[ -n "${PUBLIC_FQDN}" ] && echo "[INFO] PUBLIC_FQDN=${PUBLIC_FQDN}" || true

if command -v asterisk >/dev/null 2>&1; then
  echo "[INFO] Reloading PJSIP..."
  asterisk -rx "pjsip reload" || true
  asterisk -rx "pjsip send register ${REG_NAME}" || true

  if ! wait_for_registration 30; then
    status="$(registration_status)"
    if [[ "$status" == "Rejected" || "$status" == "Unregistered" || -z "$status" ]]; then
      echo "[WARN] Registration steckt in status=${status:-unknown}; starte Asterisk einmal neu und versuche erneut."
      systemctl restart asterisk || service asterisk restart || true
      if wait_for_asterisk_cli 90; then
        asterisk -rx "pjsip send register ${REG_NAME}" || true
        wait_for_registration 45 || true
      else
        echo "[WARN] Asterisk CLI nach Restart nicht bereit; Registrierung kann nicht erneut geprüft werden."
      fi
    fi
  fi
fi
